/* Generated by           cobc 3.2.0 */
/* Generated from         hello_world.cbl */
/* Generated at           Mar 08 2025 17:00:14 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C hello_world.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};


/* Constants */
static const cob_field c_1	= {11, (cob_u8_ptr)"Hello World", &a_1};

