/* Generated by           cobc 3.2.0 */
/* Generated from         second_test.cbl */
/* Generated at           Mar 08 2025 17:01:45 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C second_test.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x10,   1,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_3 =	{0x11,   3,   0, 0x0820, NULL};
static const cob_field_attr a_4 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_5 =	{0x10,   3,   0, 0x1000, NULL};


/* Constants */
static const cob_field c_1	= {1, (cob_u8_ptr)"1", &a_1};
static const cob_field c_2	= {14, (cob_u8_ptr)"Second program", &a_2};
static const cob_field c_3	= {5, (cob_u8_ptr)"NUM: ", &a_2};
static const cob_field c_4	= {3, (cob_u8_ptr)"X: ", &a_2};
static const cob_field c_5	= {3, (cob_u8_ptr)"255", &a_5};


/* Decimal constants */
static	cob_decimal	kc_1;
static	cob_decimal	*dc_1 = NULL;

