/* Generated by           cobc 3.2.0 */
/* Generated from         second_test.cbl */
/* Generated at           Mar 08 2025 17:01:45 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C second_test.cbl */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE		"second_test.cbl"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Mar 08 2025 17:01:45"
#define  COB_MODULE_DATE		20250308
#define  COB_MODULE_TIME		170145

/* Global variables */
#include "second_test.c.h"

/* Function prototypes */

COB_EXT_EXPORT int		sec (void);
static int		sec_ (const int);
static void		sec_module_init (cob_module *module);

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'sec' */

/* ENTRY 'sec' */

int
sec ()
{
  return sec_ (0);
}

static int
sec_ (const int entry)
{
  /* Program local variables */
  #include "second_test.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (1, &d_0);

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 9         : Entry     sec                     : second_test.cbl */
  l_2:;

  /* Line: 9         : DISPLAY            : second_test.cbl */
  cob_display (0, 1, 1, &c_2);

  /* Line: 10        : COMPUTE            : second_test.cbl */
  cob_decimal_set_ullint (d_0, ((unsigned short)COB_BSWAP_16(*(short *)(b_18))));
  cob_decimal_add (d_0, dc_1);
  cob_decimal_get_field (d_0, &f_18, 4);

  /* Line: 11        : DISPLAY            : second_test.cbl */
  cob_display (0, 1, 2, &c_3, &f_18);

  /* Line: 13        : DISPLAY            : second_test.cbl */
  cob_display (0, 1, 2, &c_4, cob_intr_numval (&f_17));

  /* Line: 14        : CALL               : second_test.cbl */
  cob_glob_ptr->cob_call_params = 0;
  cob_glob_ptr->cob_stmt_exception = 0;
  if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
    if (unlikely(call_hello_world.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
  {
    call_hello_world.funcvoid = cob_resolve_cobol ("hello_world", 0, 1);
  }
  b_2 = ((int (*)(void))call_hello_world.funcint) ();

  /* Program exit */

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  sec_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field DEF-X */
  *(cob_u8_ptr)(b_17) = (unsigned char)'a';

  /* initialize field DEF-NUM */
  cob_move ((cob_field *)&c_5, &f_18);


  /* Set Decimal Constant values */
  dc_1 = &kc_1;
  cob_decimal_init (dc_1);
  cob_decimal_set_field (dc_1, (cob_field *)&c_1);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  call_hello_world.funcvoid = NULL;
  b_2 = 0;
  cob_module_free (&module);

  initialized = 0;

  P_clear_decimal:
  /* Clear Decimal Constant values */
  cob_decimal_clear (dc_1);
  dc_1 = NULL;

  return 0;

}

/* End PROGRAM-ID 'sec' */

/* Initialize module structure for sec */
static void sec_module_init (cob_module *module)
{
  module->module_name = "sec";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())sec;
  module->module_cancel.funcptr = (void *(*)())sec_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 0;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

